### ISSUE TITLE
Error when running python -m iopenscad.install installation step

### ISSUE THREAD

**Issue by x86girl** [pschatzmann/jupyter-openscad-kernel#10]
I'm having trouble when trying to install jupyter-openscad-kernel.

Using a Python 3.10.4 venv, I could not install jupyter-openscad-kernel.
Reproducing steps:

* Installed openscad
* Created a venv
```
pip install --upgrade pip
pip install jupyter-openscad-kernel
python -m iopenscad.install
```
When running `python -m iopenscad.install`, I'm getting:
```
priscila@Hyrule:~/3d/jupyter-openscad-kernel$ python3 -m iopenscad.install
/home/priscila/3d/jupyter-openscad-kernel/iopenscad/install.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import pathlib, os, distutils.core, setuptools
sh: 1: jupyter: not found
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/priscila/3d/jupyter-openscad-kernel/iopenscad/install.py", line 22, in <module>
    main()
  File "/home/priscila/3d/jupyter-openscad-kernel/iopenscad/install.py", line 19, in main
    raise Exception('Could not install kernelspec {}'.format(cmd))
Exception: Could not install kernelspec jupyter kernelspec install /home/priscila/3d/jupyter-openscad-kernel/iopenscad/openscad
```
Installed packages:
``` 
priscila@Hyrule:~/3d/jupyter-openscad-kernel$ pip freeze 
anyio==3.6.1
apt-xapian-index==0.49
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
attrs==22.1.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
blinker==1.4
certifi==2022.6.15
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.1.1
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
dbus-python==1.2.18
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
distro==1.7.0
distro-info===1.1build1
entrypoints==0.4
executing==0.10.0
fastjsonschema==2.16.1
fuse-python==1.0.2
gpg===1.16.0-unknown
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
ipykernel==6.15.1
ipython==8.4.0
ipython-genutils==0.2.0
ipywidgets==8.0.1
jedi==0.18.1
jeepney==0.7.1
Jinja2==3.1.2
json5==0.9.10
jsonschema==4.14.0
jupyter==1.0.0
jupyter-client==7.3.4
jupyter-console==6.4.4
jupyter-core==4.11.1
jupyter-openscad-kernel @ file:///home/priscila/3d/jupyter-openscad-kernel
jupyter-server==1.18.1
jupyterlab==3.4.5
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
jupyterlab-widgets==3.0.2
keyring==23.5.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lxml==4.9.1
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==0.8.4
more-itertools==8.10.0
nbclassic==0.4.3
nbclient==0.6.6
nbconvert==6.5.3
nbformat==5.4.0
nest-asyncio==1.5.5
netifaces==0.11.0
notebook==6.4.12
notebook-shim==0.1.0
oauthlib==3.2.0
olefile==0.46
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pathlib==1.0.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
prometheus-client==0.14.1
prompt-toolkit==3.0.30
psutil==5.9.1
ptyprocess==0.7.0
pure-eval==0.2.2
pycairo==1.20.1
pycparser==2.21
pycups==2.0.1
Pygments==2.13.0
PyGObject==3.42.1
PyJWT==2.3.0
pylibacl==0.6.0
pyparsing==2.4.7
PyQt5==5.15.6
PyQt5-sip==12.9.1
pyrsistent==0.18.1
python-apt==2.3.0+ubuntu2.1
python-dateutil==2.8.2
python-debian===0.1.43ubuntu1
pytz==2022.2.1
pyxattr==0.7.2
PyYAML==5.4.1
pyzmq==23.2.1
qtconsole==5.3.1
QtPy==2.2.0
reportlab==3.6.8
requests==2.28.1
SecretStorage==3.3.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.2.post1
stack-data==0.4.0
systemd-python==234
terminado==0.15.0
tinycss2==1.1.1
tornado==6.1
traitlets==5.3.0
ubuntu-advantage-tools==27.9
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.11
usb-creator==0.3.7
wadllib==1.3.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.3
widgetsnbextension==4.0.2
xkit==0.0.0
zipp==1.0.0
```

Can you help me?

**Comment by pschatzmann** [comment]
That's strange: by default the kernel specs go to /usr/local/share/jupyter/kernels
When I run python -m iopenscad.install
I am getting
[InstallKernelSpec] Removing existing kernelspec in /usr/local/share/jupyter/kernels/openscad
[InstallKernelSpec] Installed kernelspec openscad in /usr/local/share/jupyter/kernels/openscad

I would not know why you get /home/priscila/3d/jupyter-openscad-kernel/iopenscad/openscad

Did you run the pip install jupyterlab ?
What do you get when you do a ls /home/priscila/3d/jupyter-openscad-kernel/ ?
is the jupyter command working ?

Alternativly you can just start the docker image: https://hub.docker.com/r/pschatzmann/iopenscad

**Comment by x86girl** [comment]
I tried the docker image and it worked perfectly, thanks!
