### ISSUE TITLE
Support Pipenv environments

### ISSUE THREAD

**Issue by lyndsysimon** [pschatzmann/jupyter-openscad-kernel#5]
I’m using Pipenv to manage my virtual environment for jupyter, and got the following error when attempting to run `pipenv run python -m iopenscad.install`:

```
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lyndsy/.local/share/virtualenvs/cad-SrIVxOL8/lib/python3.8/site-packages/iopenscad/install.py", line 22, in <module>
    main()
  File "/home/lyndsy/.local/share/virtualenvs/cad-SrIVxOL8/lib/python3.8/site-packages/iopenscad/install.py", line 19, in main
    raise Exception('Could not install kernelspec {}'.format(cmd))
Exception: Could not install kernelspec jupyter kernelspec install /home/lyndsy/.local/share/virtualenvs/cad-SrIVxOL8/lib/python3.8/site-packages/iopenscad/openscad
```

I’ve temporarily resolved this by symlinking the environment’s share directory to where the library is expecting it: `sudo ln -s ~/.local/share/virtualenvs/cad-SrIVxOL8/share/jupyter /usr/local/share/jupyter`

**Comment by pschatzmann** [comment]
I think sudo should do the trick:
sudo python -m iopenscad.install
